plugins:
  discourse_follow_enabled:
    default: false
    client: true
  follow_show_statistics_on_profile:
    default: true
    client: true
  follow_notifications_enabled:
    default: true
    client: true
  follow_followers_visible:
    enum: "FollowPagesVisibility"
    default: everyone
  follow_following_visible:
    enum: "FollowPagesVisibility"
    default: everyone
  default_notify_me_when_followed:
    default: true
  default_notify_followed_user_when_followed:
    default: true
  default_notify_me_when_followed_replies:
    default: false
  default_notify_me_when_followed_creates_topic:
    default: false
  default_allow_people_to_follow_me:
    default: true
