plugins:
  discourse_follow_enabled:
    default: true
    client: true
  follow_show_statistics_on_profile:
    default: true
    client: true
  follow_notifications_enabled:
    default: true
    client: true
  follow_followers_visible:
    type: enum
    default: everyone
    choices:
      - no-one
      - self
      - staff
      - trust_level_4
      - trust_level_3
      - trust_level_2
      - trust_level_1
      - trust_level_0
      - everyone
  follow_following_visible:
    type: enum
    default: everyone
    choices:
      - no-one
      - self
      - staff
      - trust_level_4
      - trust_level_3
      - trust_level_2
      - trust_level_1
      - trust_level_0
      - everyone
